# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - npm run test
  analyze:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - npm audit

workflows:
  # Name the workflow "welcome"
  test_pipeline:
    # Run the welcome/run job in its own container
    jobs:
      - build
      - test: 
          depends:
            - build
      - analyze:
          depends:
            - test
